# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-17 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_prestamo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Si el descuento se encuentra vigente', verbose_name='Activo')),
                ('fijo', models.BooleanField(default=False, help_text='Si es fijo para todos los meses', verbose_name='Fijo')),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal')], help_text='Información Histórica', max_length=100, verbose_name='Tipo Descuento')),
                ('imprimir', models.BooleanField(default=False, help_text='Si se imprime en el Rol', verbose_name='Imprimir')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Descuento_Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Descuento')),
                ('descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_libros.Descuento', verbose_name='Descuento')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Si se encuentra vigente', verbose_name='Activo')),
                ('imprimir', models.BooleanField(default=False, help_text='Si se imprime en el Rol', verbose_name='Imprimir')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso_Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor ingreso')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_libros.Ingreso', verbose_name='Ingreso')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Periodo_Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('ENERO', 'ENERO'), ('FEBRERO', 'FEBRERO'), ('MARZO', 'MARZO'), ('ABRIL', 'ABRIL'), ('MAYO', 'MAYO'), ('JUNIO', 'JUNIO'), ('JULIO', 'JULIO'), ('AGOSTO', 'AGOSTO'), ('SEPTIEMBRE', 'SEPTIEMBRE'), ('OCTUBRE', 'OCTUBRE'), ('NOVIEMBRE', 'NOVIEMBRE'), ('DICIEMBRE', 'DICIEMBRE')], max_length=15, verbose_name='Mes')),
                ('anio', models.CharField(help_text="Ejemplo: '2010'", max_length=4, verbose_name='Año')),
                ('max_dias', models.IntegerField(default=30)),
                ('emitido', models.BooleanField(default=False, verbose_name='Completado')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Rol_Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trabajados', models.IntegerField(default=30, verbose_name='Días trabajados')),
                ('aporte_patronal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Aporte Patronal')),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total ingresos')),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total descuentos')),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total a pagar')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('periodo_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_libros.Periodo_Rol', verbose_name='Periodo')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partida_rol', to='app_prestamo.Persona', verbose_name='Partida')),
            ],
            options={
                'verbose_name': 'Rol de Pago',
                'verbose_name_plural': 'Roles de Pago',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='ingreso_rol',
            name='rol_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_libros.Rol_Pago', verbose_name='Rol de Pago'),
        ),
        migrations.AddField(
            model_name='descuento_rol',
            name='rol_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_libros.Rol_Pago', verbose_name='Rol de Pago'),
        ),
    ]
