# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-15 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, verbose_name='CÉDULA')),
                ('nombres', models.CharField(max_length=200, verbose_name='NOMBRES')),
                ('apellidos', models.CharField(max_length=200, verbose_name='APELLIDOS')),
                ('telefono', models.CharField(max_length=15, verbose_name='TELÉFONO')),
                ('tipo', models.CharField(choices=[('empleado', 'Empleado'), ('trabajador', 'Trabajor')], max_length=25)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='SUELDO MENSUAL')),
            ],
        ),
    ]
